### ISSUE TITLE
Diamond tools don't work with veinminer on the 1.16 version of the datapack

### ISSUE THREAD

**Issue by agow100** [Elemend/Vein-Miner-Unified#12]
Pretty much the title. Tested on a 1.16.1 server.
The enchantment can't be applied, and tools that had it from before don't work.
wood, gold, stone, iron and netherite still work however, including shears.

**Comment by Elemend** [comment]
Huh, ok... No Idea why the enchantment wouldn't get applied. I can only try singleplayer 1.16.1 in a fresh world and it worked there.
As for diamond tools not working, I definitely did something wrong there. I updated the pack now. They should work for again like they should.

**Comment by agow100** [comment]
Thanks for the quick fix
