### ISSUE TITLE
Diamond Tools Durability Resetting

### ISSUE THREAD

**Issue by Ptopman** [Elemend/Vein-Miner-Unified#14]
So far with Diamond pickaxes and Diamond Shovel, When you mine regular stone the durability will decrease normally, When you vein mine an resource, the durability will jump up to nearly full. So far only seeing this with diamond.

I have the enchantment feature turned off, As well I edited the mineable blocks to only ores.

![VeinMinerBug](https://user-images.githubusercontent.com/26233696/85895597-fd568400-b7c4-11ea-8ebb-f6af7037ac98.png)

**Comment by Elemend** [comment]
I think I made a mistake with the commands there. I edited the pack to fix this. Download it again, and it should work.

**Comment by Ptopman** [comment]
Yep, Looks like that Fixed it. Thank you for the fast fix!
