### ISSUE TITLE
1.16: Veins not mined and nether gold ore drops stone buttons

### ISSUE THREAD

**Issue by OliverDudgeon** [Elemend/Vein-Miner-Unified#15]
I run a server that was running the datapack on 1.15.2. After updating to the 1.16 version (I just deleted the datapack and added the 1.16 version in), it not longer works properly.

The teleport feature still works.
I have the enchantment off disabled.
No blocks are vein mined.
So far only gold ore and other new nether blocks drop buttons instead. 

Any ideas how to fix this? Thanks for your time working on this project. My server members really appreciate it!

**Comment by Elemend** [comment]
Are there any errors in the game log?

**Comment by OliverDudgeon** [comment]
When testing with a copy of my server world in single player I don't get any errors in my client console.

**Comment by OliverDudgeon** [comment]
I've tried removing all my other datapacks and all scoreboards to reset things but it functions the same when I reload veinminer back in at the end.

**Comment by OliverDudgeon** [comment]
Basalt will vein mine but it drops stone buttons instead

**Comment by OliverDudgeon** [comment]
I think I've got it working now. I have no idea why but deleting my `world/data/chunks.dat` seems to fix it.
