### ISSUE TITLE
Not Working on Server

### ISSUE THREAD

**Issue by Qbiksus** [Elemend/Vein-Miner-Unified#19]
I have installed this datapack on my minecraft server (Fabric 1.16.1), and it is installed (shows up in the advancements and can use it's commands) but it will not let me veinmine. I have tried it on singleplayer with and without fabric with no luck. Logs don't say anything.

**Comment by Elemend** [comment]
What you didn't mention is if you sneaked while mining. Because you mentioned you can't get it to work even without fabric...

**Comment by Qbiksus** [comment]
I was. I figured it would be a given that I was sneaking.

**Comment by Elemend** [comment]
I have no Idea what to do then.

**Comment by Elemend** [comment]
So I installed Fabric together with Sodium and Phosphor (Optimization mods) and I can use this data pack just fine. So whatever it is that breaks it for you may be what fabric mods you have installed.

**Comment by Qbiksus** [comment]
It wouldn't work on vanilla 1.16.1 for me either. I guess if you can't reproduce it you can't do much. Thank you though!

**Comment by Elemend** [comment]
Did you redownload it and tried again? Since two weeks ago I edited the chunk setup a bit. Maybe that'd fix it for you?

**Comment by Qbiksus** [comment]
I won't be able to try until the 21st because my phone is out of hotspot data and I can't open 1.16.1 because the launcher needs to download stuff for it

**Comment by Nocturnal42** [comment]
I tried this on a vanilla 1.16.2 server, it shows as being loaded. I can use the /function vm:custom and I can enchant a pick, but vein mining does not work.

**Comment by Elemend** [comment]
Are the forceloaded chunks at -30000000 7776 actually loaded? Is there a shulker box at -30000000 0 7777?
Have you tried turning it off and on again?

**Comment by Nocturnal42** [comment]
-30000000 0 7777 is in chunk -1875000 486, and according to forceload query, it is loaded. There is however no shulker box, there is a bedrock block.

**Comment by Nocturnal42** [comment]
And suddenly there is one, and it's working. I was testing out a variety of different world, created under different conditions, and the datapack worked fine in all of them. When I went back to my main world the shulker box had appeared.
