### ISSUE TITLE
Basalt turns into Stone Buttons

### ISSUE THREAD

**Issue by Baxh** [Elemend/Vein-Miner-Unified#21]
Good day, perhaps I have messed up something or not but when Mining Basalt Structures from the Nether they all turn into Stone Buttons when shift mining, how can I fix this?

**Comment by Elemend** [comment]
Was the chunk in the nether not forceloaded? You can check this by running a command in chat, actually:
`execute in minecraft:the_nether if block -30000000 0 7777 minecraft:yellow_shulker_box`
which should return true.

**Comment by Baxh** [comment]
it returns "Test Failed" and it goes beyond the world border limit I tried to expand it but I get the message "World Border cannot be bigger than 60,000,000 blocks wide

**Comment by Elemend** [comment]
The chunk at that position should be forceloaded. The fact that it isn't breaks... pretty much everything. Now the question is wether the chunk was unloaded or if it wasn't ever loaded at all.
Execute this command to load the chunk manually: `execute in minecraft:the_nether run forceload add -30000000 7776`
and then execute the command to check for the shulker box again. If that still returns false then the chunk has never been loaded at all and the setup functions failed to run.

**Comment by Baxh** [comment]
![image](https://user-images.githubusercontent.com/11514571/89109692-217f3380-d409-11ea-8183-e4fafd61a461.png)

**Comment by Elemend** [comment]
Weird... Does this data pack work in any other dimension? Because from the debugging you did here nothing should work at all. Or rather I'd be surprised that it would work in the overworld, but not in the nether.

**Comment by Elemend** [comment]
I updated the pack. This Issue should be fixed now.

**Comment by Baxh** [comment]
I'll check it out! thanks!

**Comment by Baxh** [comment]
Yes it seems it works now, it says "Test Passed" and after testing it out on the other Dimensions, Nether and End works very well! thanks a lot!

**Comment by Elemend** [comment]
Alright! Then I'm closing this
