### ISSUE TITLE
Not working with *Advanced Mining Dimension* mod @ 1.16.1 @

### ISSUE THREAD

**Issue by DPSCryptic** [Elemend/Vein-Miner-Unified#22]
First, i wanna thank you for this 'mod', works quite well in the overworld, i have not tried it in the nether or end yet but i tried this on a private server and it doesnt work in the mining dimension from the mod in the title

is this something i could configure myself, or is this just a bug

**Comment by DPSCryptic** [comment]
i also don't know if you support modded minecraft, but this is all we got for the latest

**Comment by Elemend** [comment]
If it works in modded minecraft, cool. But if it doesn't, ¯\\\_(ツ)_/¯. 
Still, if you manage to have a forceloaded chunk at the same position with the same blocks at the same coordinates as the one in the overworld there's a chance it works?

**Comment by DPSCryptic** [comment]
sadly the mod generates a cave world, so it wouldnt be really possible to match chunks

**Comment by Elemend** [comment]
What I meant with this is the chunk `-30000000 7776` being forceloaded. You could add that with a command: `forceload add -30000000 7776` in the respective dimension.
and in that chunk there is a shulker box which can be placed there with a command:
`setblock -30000000 0 7777 minecraft:yellow_shulker_box`
the chunk being loaded and the shulker box at that exact position are needed for this data pack to work.

**Comment by DPSCryptic** [comment]
ohh damn, that worked like a charm

can i add ores that can be veinmined?

**Comment by Elemend** [comment]
no. I mean propably not, because I don't know how or if commands interact with modded blocks. And even then it's a bit of work.
