### ISSUE TITLE
I can't vein mine even though I'm shifting

### ISSUE THREAD

**Issue by Kirorno** [Elemend/Vein-Miner-Unified#24]
well... the title no need to read this. btw this is a question on how to fix the issue not just a reminder or smthing.

**Comment by Elemend** [comment]
This is controlled through a predicate. Are you using any modifications which maybe break those?

**Comment by pbhj** [comment]
The readme wasn't entirely clear to me when I started (very recently), the default is to only do veinmining with enchanted tools. You have to do "/function vm:custom" and then it shows the options (as in the readme). You actually click the text in the console to change the settings, which is a little weird: for me the console closed immediately when I used the mouse, but reopen it with "/" and then click the text and it still works: click "[disable]" under "echantment option" and you can use it with ordinary tools.

Perhaps that was your problem too?

**Comment by Kirorno** [comment]
nah wasn

**Comment by Kirorno** [comment]
nah it wasn't my issue but i just removed some datapacks and voila

**Comment by Elemend** [comment]
so the error was an something from another data pack?

Can this be closed then?
