### ISSUE TITLE
Yellow Shulker Box?

### ISSUE THREAD

**Issue by NayanMori** [Elemend/Vein-Miner-Unified#29]
I added the 1.16.1 version to my mooded forge world and for some reason when I mine anything with it, my tool goes into a yellow shulker box? It just appears in my inventory right after I use it with my pickaxe in it. Is this an issue with the datapack or somehow related to a mod I have installed?

**Comment by Elemend** [comment]
This is definetly a problem with your mods. The yellow shulker box loot table gets overridden by one of your mods, thus creating this problem.
