### ISSUE TITLE
1.14 - vein mining activating on non-ores/wood

### ISSUE THREAD

**Issue by TheSofas** [Elemend/Vein-Miner-Unified#3]
In the latest update, the 9x9x9 issue with ores was fixed, but now every type of block that is not ore is being mined in a full 9x9x9 area.

I have tested this with the following:

- All Stones
- Netherrack
- Player-Placed Wooden Planks
- Dirt and Grass 
- Sand and Gravel

I assume it works on more blocks, but couldn't be bothered. 

This happens with 100% reproduction rate, with no conflicting data packs. I have the enhancement option off, and the hunger debuff off.

My guess is this is just a typo resulting from changing things around from the last update.

**Comment by Elemend** [comment]
I'm not sure if I understood the problem correctly. This Vein Miner will always try to mine the whole 9x9x9 area of the same type of block. All Blocks in this area that are not of the same type of the one you mined should not be mined too. Is that the problem that it ignores other different blocks that shouldn't be mined?

**Comment by Elemend** [comment]
I think you misinterpreted this Vein Miner as being only useable for ores. If this is correct, there wasn't an Issue. I understand this as not being an actual Issue.
