### ISSUE TITLE
Request: show how to change the range of the veinmining in the wiki:

### ISSUE THREAD

**Issue by w1lldu** [Elemend/Vein-Miner-Unified#30]
I'm sure somewhere in the code theres a place that stops the veinmining from going any further, but I can't find it, and I think it would be convenient to know.

**Comment by RGFTheCoder** [comment]
I'm pretty sure that it just breaks until the tool is at 0 or 1 durability (Right before breaking)

**Comment by w1lldu** [comment]
“Mine Blocks while sneaking and all identical Blocks that are orthogonally connected to the one mined, up to a distance of 4 Blocks will be mined too.”

**Comment by joveice** [comment]
Yea I would like to change this too. Sometimes I mine out big chunks that I have no controll over.

**Comment by MiloC37** [comment]
This would be pretty great, even if it is just a command to do certain sizes like 3x3 or 5x5
