### ISSUE TITLE
World laggy, chunk loading slow and saving world take forever as well as laoding the world.

### ISSUE THREAD

**Issue by MartinSekeras** [Elemend/Vein-Miner-Unified#33]
This datapack has destroyed my world. It takes 5 minutes to load me into the world during which time i just sit in void. Chunk loading is super slow and saving takes even longer and sometimes crashes.

**Comment by WolfTM** [comment]
Same issue here, Would really want to see this fixed. It is annoying...
@Elemend

**Comment by WolfTM** [comment]
@Elemend @MartinSekeras 

I fixed the issue on my side.
My problem with this on 1.16.3 was optifine.
I just used 1.16.3 vanilla and it works without issues.

So for 1.16.3 Optifine is the issue.

**Comment by Elemend** [comment]
The fact that you have these problems sucks, of course... but are you absolutely sure it's related to this data pack? From what you wrote I can't tell wether or not Minecraft runs bad already for you. And I also can't tell as to what would cause the Issue. This datapack uses loaded chunks at the worldborder and that is a potential source of this. Unfortunately they are needed to make this data pack work in the first place so I really don't know what to do about it from my end.

**Comment by WolfTM** [comment]
> The fact that you have these problems sucks, of course... but are you absolutely sure it's related to this data pack? From what you wrote I can't tell wether or not Minecraft runs bad already for you. And I also can't tell as to what would cause the Issue. This datapack uses loaded chunks at the worldborder and that is a potential source of this. Unfortunately they are needed to make this data pack work in the first place so I really don't know what to do about it from my end.

Hmm also not sure anymore, I used it without all othjer datapacks and it worked finally. It might be to much datapacks or overriding ones
