### ISSUE TITLE
1.16.3 - VeinMiner With Optifine (Breaks Game)

### ISSUE THREAD

**Issue by WolfTM** [Elemend/Vein-Miner-Unified#36]
Hello,

Description: Using this datapack on 1.16.3 with optifine and a few other datapacks breaks the game world loading and crashes.
Version: 1.16.3
Recommended: Do **NOT** use optifine 1.16.3 with this datapack andd a few others active.
Solution: Use 1.16.3 Vanilla instead of optifine

Note: All current optifine 1.16.3 version from the current date **break the game while this datapack with a few other datapacks** is active!

The other datapacks from VanillaTweaks with this one caused the issue.

**Comment by kuolemax** [comment]
> Hello,
> 
> Description: Using this datapack on 1.16.3 with optifine breaks the game world loading and crashes.
> Version: 1.16.3
> Recommended: Do **NOT** use optifine 1.16.3 with this datapack active.
> Solution: Use 1.16.3 Vanilla instead of optifine
> 
> Note: All current optifine 1.16.3 version from the current date break the game while this datapack is active!

I use OptiFine_1.16.3_HD_U_G3 and this datapack, is OK.

**Comment by WolfTM** [comment]
Not if you use a few others.

I tested it also alone with optifine and it caused an issue.
This is also because Optifine is not the best anymore and this datapack has just bad support.

I moved on with mods and got my own private mod for VeinMiner in 1.16+ format support.
