### ISSUE TITLE
why would you put stone on the whitelist?

### ISSUE THREAD

**Issue by lunchboxxx19** [Elemend/Vein-Miner-Unified#37]
seriously? what made you think that was a good idea?

a smarter idea would have been to put it in the blacklist. its the most abundant source in the game. vein mining is for ores not crappy stone. ui dont know how many times ive accidently hit stone and had to fill an entire area back in due to this piss poor decision

**Comment by Elemend** [comment]
just wait till you find out about the >500 Blocks you can veinmine too

If you don't like it, use another veinminer datapack that limits itself to ores only. there are at least 5 on planetminecraft, I'm sure
