### ISSUE TITLE
Yellow Shulker Boxes?

### ISSUE THREAD

**Issue by rsmalec** [Elemend/Vein-Miner-Unified#38]
I've been using this datapack with a few others in my single player world for several weeks.   Suddenly, my tool is being put in a yellow shulker box, almost every time.  But not every time.  I've tried to rule out when/why it seems to be happening but can't see a pattern - e.g. it doesn't seem to be tied to durability.
Why is it happening?  I can see that the yellow shulker box loot table was modified.  So this is intentional?  But I couldn't find any other function that purposely gives you a yellow shulker box.

**Comment by Elemend** [comment]
If you have any data pack that alters the yellow shulker box loot table this vein miner breaks. Weird that if that's the reason it would sometimes work...

Are you playing with mods? or anything that interferes with vanilla minecraft? are you even in 1.16.4?
