### ISSUE TITLE
1.14.2 Support

### ISSUE THREAD

**Issue by MarkimusDev** [Elemend/Vein-Miner-Unified#4]
Data pack does not seem to work on 1.14.2. It loads, and the vm:custom command works, advancement is showing up, but sneaking and breaking trees with an iron axe does nothing.

**Comment by Elemend** [comment]
I can't recreate that. Is the tool enchanted or not? What is the variable set to in vm:custom? If you click the disable/enable of the Enchantment option in vm:custom these messages will pop up:
"Set [vm_calc] for #vm_ench to 1" - for making it work the enchanted tools.
"Set [vm_calc] for #vm_ench to 0" - for making it work without the enchantment.
