### ISSUE TITLE
Installing Issue On 3rd Party Server

### ISSUE THREAD

**Issue by DemonsGunnar** [Elemend/Vein-Miner-Unified#40]
I have been trying to add this to my vanilla server thats hosted by MCProHosting, Ive installed it like every other data pack, Ive done zipped or unzipped, Its the correct version. It has the advancement, and is in the /datapacks enabled, but just doesnt work :/. Is there something Im doing wrong?

**Comment by Korinin38** [comment]
Have you tried disabling Enchantment Option?
With this option enabled, vein mining only works with tools that are enchanted in specific way (as stated in README).
