### ISSUE TITLE
a REAL enchantment, please?..

### ISSUE THREAD

**Issue by alfuken** [Elemend/Vein-Miner-Unified#41]
Can you, please, add a proper enchantment to this mod? Throwing a somewhat easily obtainable item with not spending tons of XP to find that one enchantment you need feels like... cheating. Or at least make it configurable what to throw at it - a nether star, or maybe a ghast tear, but an endereye...

**Comment by Elemend** [comment]
I'm not a modder. this is a data pack, I don't change the gamecode
