### ISSUE TITLE
Compatibility Issue With CoreProtect 

### ISSUE THREAD

**Issue by HydroMuffin** [Elemend/Vein-Miner-Unified#44]
Hello, I'm running into a problem on a spigot server where we are using CoreProtect for anti-grief protection.
Our problem is that blocks broken using veinminer are not logged in CoreProtect and we are unable to rollback the blocks.
The initial block that is broken is replaced but any adjacent blocks that are broken by veinminer are not.
Any help resolving this issue would be greatly appreciated, thank you.

**Comment by Elemend** [comment]
I'm afraid it's commands doing the mining, not a player. that's why it isn't logged. This isn't something that can't be resolved. This is just incompatible.
