### ISSUE TITLE
vein miner not working but teleporting items feature works

### ISSUE THREAD

**Issue by ZombieKiller9549** [Elemend/Vein-Miner-Unified#45]
I'm trying to play the 1.17 update with the Vein miner data pack, i've done all of the steps (extracting it) and went through verifying that all of the packs were there. went into the game and did /function vm:custom (as i was told) but there's not a part of the text that tells you what button (keybind) to press for it to work. Did i do anything wrong? 

step 1: downloading it
step 2: extracting the file(s) to the datapacks folder
step 3: loading the world
step 4: opening it as a LAN world to activate cheats
step 5: ran /function vm:custom (and choose my settings from 3 options)
step 6: ran F3 + T (to reload minecraft to be safe) 

step 7: issues still persist after testing it after few worlds.

**Comment by Elemend** [comment]
Well, I hope the new Version will fix this for you.
