### ISSUE TITLE
Unknown scoreboard objective

### ISSUE THREAD

**Issue by RadNotRed** [Elemend/Vein-Miner-Unified#46]
When I run /function vm:custom and click any of the options, it says "Unknown scoreboard objective 'vm_calc'
When I manually make one, it says the objective is read only

**Comment by Elemend** [comment]
seems like you have something else going on messing up your minecraft installation. this has nothing to do with this data pack.

**Comment by RadNotRed** [comment]
is this only for client or is this for servers

**Comment by Elemend** [comment]
This should work on both. But server software famously messes with commands for whatever reason.
Your server is modded, seeing the objective is "read only" after you manually made it. This objective should be a dummy scoreboard, just fyi... and you shouldn't even have to add it yourself. Something on your server is preventing this data pack from adding the objective automatically. And even if that scoreboard would exist, the data pack would probably not work either.

**Comment by RadNotRed** [comment]
alrighty thank you, ill figure it out
