### ISSUE TITLE
1.18.1 | Item disappears after vein mining 

### ISSUE THREAD

**Issue by DarthEnigme** [Elemend/Vein-Miner-Unified#49]
Breaking the blocks with the vein miner, makes the pickaxe dissapear.
Is there any fix about it

**Comment by spunkyjethro** [comment]
I had this happen as well, however, the datapack has yet to be updated to 1.18 so there will be issues.

**Comment by Elemend** [comment]
I have no plans to update this to 1.18.

**Comment by H1k4r1cr** [comment]
I fell in love with this datapack. Too bad there is an update for 1.18.
My knowledge with reach the point of being able to do it myself.
