### ISSUE TITLE
1.14.3 Support

### ISSUE THREAD

**Issue by BobDaGecko** [Elemend/Vein-Miner-Unified#5]
I know 1.14.3 came out not to long ago but I was trying this pack specifically with logs but it does not work. What can I do to fix the pack? I have done the vm:custom command and done every combination and I have tried many blocks. I would like to note I did edit the pack so only certain blocks would work. Please let me know what you can do about this as this is a great pack.

**Comment by Myafosya** [comment]
I've noticed the same problem. 
Datapack doesn't work when you enable enchantments.

**Comment by Elemend** [comment]
I'm able to veinmine logs, so I'm not sure what to do from my End. 
How does your axeblocks.json block tag look like, exactly?

**Comment by BobDaGecko** [comment]
[vein_miner_u_1.14.zip](https://github.com/Elemend/Vein-Miner-Unified/files/3370950/vein_miner_u_1.14.zip)

Thats's my edited zip file if you would like to look through that.

**Comment by Elemend** [comment]
You did leave commas on the last entires in the block tags. This caused the block tags to be considered invalid by Minecraft and broke the datapack as a result. 
I deleted the commas and tried it myself, it works for logs now.
[vein_miner_u_1.14.zip](https://github.com/Elemend/Vein-Miner-Unified/files/3371984/vein_miner_u_1.14.zip)

**Comment by BobDaGecko** [comment]
Thanks, I deleted all unnecessary commas and it fixed the pack. Thanks for your help the pack works great now. Sorry for the inconvenience it was my mistake.

**Comment by BobDaGecko** [comment]
Thanks, I deleted all unnecessary commas and it fixed the pack. Thanks for your help the pack works great now. Sorry for the inconvenience it was my mistake.
