### ISSUE TITLE
1.14.3 Block swap

### ISSUE THREAD

**Issue by Myafosya** [Elemend/Vein-Miner-Unified#6]
Something weird happened. I tried to veinmine spruce leaves with scissors that had 0 durability and it gave me 25 chests.
My settings are: 
enchantments - 0
hunger - 0
item teleport - 1

**Comment by Elemend** [comment]
Yes, that was partly my fault, but also partly Minecrafts fault. 
My error was that when I read the Durability on a tool which has 0 durability, the math behind it messes up and it thinks the tool has max durability instead.
The Error from Minecraft itself is that there is no itemdrop from shears which have a durability of 0.

I updated the pack with the fix.
