### ISSUE TITLE
Fails to upload to realm (1.14.4)

### ISSUE THREAD

**Issue by MineMario101** [Elemend/Vein-Miner-Unified#7]
This is a really great data pack that has so many great uses. Thank you for developing it for 1.14. When we attempt to upload this data pack to our realm it constantly fails to upload. We have other data packs on the realm that were able to download just fine. We are attempting to add it as a compressed file. I've tested it in singleplayer survival and it works with no problems.

**Comment by Elemend** [comment]
I will not be able to fix this, I'm afraid. There is an old bug report, maybe with the Issue you encounter:
https://bugs.mojang.com/browse/REALMS-1128

If you find any errors, that would be good to know as well.
